//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRKTPTUR6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FRKTPTUREntities : DbContext
    {
        public FRKTPTUREntities()
            : base("name=FRKTPTUREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilet> Bilet { get; set; }
        public virtual DbSet<BiletSatış> BiletSatış { get; set; }
        public virtual DbSet<Fatura> Fatura { get; set; }
        public virtual DbSet<Ilce> Ilce { get; set; }
        public virtual DbSet<Muhasebe> Muhasebe { get; set; }
        public virtual DbSet<Müşteri> Müşteri { get; set; }
        public virtual DbSet<Otobüs> Otobüs { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Sefer> Sefer { get; set; }
        public virtual DbSet<Seferİptal> Seferİptal { get; set; }
        public virtual DbSet<Sehirler> Sehirler { get; set; }
        public virtual DbSet<Subeler> Subeler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
