//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRKTPTUR6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muhasebe
    {
        public int Muhasebe_ID { get; set; }
        public int Fatura_ID { get; set; }
    
        public virtual Fatura Fatura { get; set; }
    }
}
