//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRKTPTUR6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Müşteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Müşteri()
        {
            this.Bilet = new HashSet<Bilet>();
        }
    
        public int Müs_ID { get; set; }
        public string MüsAd { get; set; }
        public string MüsSoyad { get; set; }
        public string MüsTelNO { get; set; }
        public string Cinsiyet { get; set; }
        public string KullanıcıAd { get; set; }
        public string Sifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilet> Bilet { get; set; }
    }
}
