//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRKTPTUR6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otobüs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Otobüs()
        {
            this.Bilet = new HashSet<Bilet>();
            this.Sefer = new HashSet<Sefer>();
        }
    
        public int Bus_ID { get; set; }
        public int Sube_ID { get; set; }
        public int Pers_ID { get; set; }
        public Nullable<int> Sefer_ID { get; set; }
        public string Plaka { get; set; }
        public byte KoltukSayısı { get; set; }
        public string BusMarka { get; set; }
        public string DoluKoltukSayısı { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilet> Bilet { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual Subeler Subeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sefer> Sefer { get; set; }
    }
}
