//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRKTPTUR6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seferİptal
    {
        public string Seferİptal_ID { get; set; }
        public int Sefer_ID { get; set; }
    
        public virtual Sefer Sefer { get; set; }
    }
}
